# Configuration for dependency review action
fail-on-severity: moderate
allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - Unicode-DFS-2016
  - MPL-2.0
  - LGPL-3.0
comment-summary-in-pr: always
