[package]
name = "bay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.7"
base64 = "0.22"
http = "1"
proto = { path = "../proto" }
rand = "0.8"
futures = "0.3"
hyper = { version = "1", features = ["http1", "server"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.38", features = ["macros", "rt-multi-thread", "signal", "sync"] }
tokio-util = { version = "0.7", features = ["codec"] }
uuid = { version = "1", features = ["v4"] }
