[package]
name = "bay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = { version = "0.8", features = ["ws"] }
base64 = "0.22"
futures = "0.3"
http = "1"
hyper = { version = "1", features = ["http1", "server"] }
proto = { path = "../proto" }
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.38", features = ["macros", "rt-multi-thread", "signal", "sync"] }
uuid = { version = "1", features = ["v4"] }
