apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bay
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute-control.yaml
  - ingressroute-control-http.yaml
  - ingressroute-wildcard.yaml
  - ingressroute-wildcard-http.yaml
