apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bay-control-http
  namespace: bay
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`bay.apps.timvw.be`) && PathPrefix(`/control`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: traefik
      services:
        - name: bay
          port: 7070
