apiVersion: v1
kind: Service
metadata:
  name: bay
  namespace: bay
spec:
  selector:
    app: bay
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: control
      port: 7070
      targetPort: control
